version: '3'
services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
